### ISSUE TITLE
Not replacing library environment variables

### ISSUE THREAD

**Issue by andrezsanchez** [hughsk/envify#15]
I'm trying to use this transform on a project, but the transform doesn't seem to be replacing the environment variables within a library (specifically React, but I don't know if that makes a difference here).

To reproduce:

``` bash
mkdir eg
cd eg

npm install -g browserify
npm install react envify
echo "require('react');" > file.js

# This ought to return no results, but it does
browserify -t [ envify --NODE_ENV production ] file.js | grep NODE_ENV
```

**Comment by Levino** [comment]
I am using gulp browserify. What is the equivalent of the "global" flag there? Anybody knows?

**Comment by stefanb2** [comment]
@Levino: excerpt from my gulpfile,js:

```javascaript
browserify(...)
    ...
    .transform('envify', {
        global:   true, // also apply to node_modules
        NODE_ENV: debug ? 'development' : 'production',
    })
    ...
    .bundle()
    ...
    .pipe(gulpif(!debug, babelMinify())) // my example uses gulp-babel-minify
    ...
```

**Comment by levino** [comment]
Meanwhile I switched to webpack. Thanks for finally answering my question though @stefanb2
