### ISSUE TITLE
doesn't seem to work with symlinked files

### ISSUE THREAD

**Issue by davidchase** [hughsk/envify#17]
So i have some files symlinked into `node_modules` more on it [here](https://github.com/substack/browserify-handbook#symlink).

That way i can `require('myServices/service');` instead of `require('../../../myServices/service')`

Unfortunately if i have something like `process.env.MY_VAR` inside that file (service.js) it will not be transformed.

Any thoughts or suggestions?

**Comment by m90** [comment]
@davidchase Did you ever get this running using command line `browserify`? Your solution works fine for me when using `browserify-middleware` but will fail just like before when I try to build a file from the command line:

```
browserify ./public/js/main.js -t jadeify -t envify > ./dist/some-module.js 
```

**Comment by m90** [comment]
Forget about it, I just needed to use `-g` instead of `-t`:

```
$ browserify ./public/js/main.js -g jadeify -g [ envify --NODE_ENV production ] > ./dist/some-module.js 
```
