### ISSUE TITLE
Can't install envify in a local environment

### ISSUE THREAD

**Issue by kingzbauer** [hughsk/envify#18]
npm ERR! peerinvalid The package envify does not satisfy its siblings' peerDependencies requirements!

Happens when I am trying out the flux example
package.json contents:
```json
 "devDependencies": {
        "jsxc": "~0.1.6",
        "browserify" : "^6.2.0",
        "reactify": "^0.15.2",
        "envify": "3.2.0",
        "jest-cli": "~0.1.17",
        "uglify-js": "~2.4.15",
        "watchify": "^2.1.1"
    },
    "scripts": {
        "start": "watchify -o js/bundle.js -v -d .",
        "build": "NODE_ENV=production browserify . | uglifyjs -cm > js/bundle.min.js",
        "test": "jest"
    },
    "browserify": {
        "transform": [
            "reactify",
            "envify"
        ]
    },
```

**Comment by hughsk** [comment]
I'm not sure what's causing this error – what's the flux example you're referring to?

**Comment by kingzbauer** [comment]
The one on this link. http://facebook.github.io/flux/docs/todo-list.html

**Comment by mcabrams** [comment]
@kingzbauer https://github.com/facebook/flux/issues/157#issue-57552811

Try that solution. This issue can probably be closed.
