### ISSUE TITLE
jstransform deprications

### ISSUE THREAD

**Issue by btd** [hughsk/envify#31]
Hello.

I would like to know plans on updating dependencies as react.js guys deprecate jstransform and esprima-fb (https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html)

Thanks.

**Comment by btd** [comment]
I just noticed PR https://github.com/hughsk/envify/pull/30.

**Comment by yoshuawuyts** [comment]
Yup, once #30 is merged any possible issues should be cleared (':
