### ISSUE TITLE
Including envify as a transform causes browserify to throw an error

### ISSUE THREAD

**Issue by toddself** [hughsk/envify#32]
This is odd.

If I do:

`browserify -t envify entrypoint.js`

it will work.

However, if I do:
`browserify('entrypoint.js').transform(require('envify')()).bundle()`

browserify will crash with:

```
Unable to build /home/user/scripto2/src/static/js/entrypoint.js path must be a string Error: path must be a string
        at /home/user/scripto2/node_modules/browserify/node_modules/resolve/lib/async.js:16:16
        at doNTCallback0 (node.js:407:9)
        at process._tickDomainCallback (node.js:377:13) { err:
       { [Error: path must be a string]
         stream:
          Labeled {
            _readableState: [Object],
            readable: true,
            domain: null,
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: true,
            _options: [Object],
            _wrapOptions: [Object],
            _streams: [Object],
            length: 1,
            label: 'deps' } } }
```

If I remove the `.transform` call everything works correctly.

browserify 10.2.6 (as well as 11.0.1)
envify 3.4.0

I've created a simple test case here: https://github.com/toddself/envify-example

if you do `node bundle.js` you'll see the error.  if you remove the call to `.transform` it'll work. (it doesn't matter if you put envify in the `.transform` call or in the `transform` keys in `package.json` -- they both fail). However, if you do `node_modules/.bin/browserify -t envify entrypoint.js` it'll work...

**Comment by yoshuawuyts** [comment]
> This is todd.

FTFY :grin:

But to answer your question: could you try doing `require('envify/custom')`, I suspect that will resolve your issue.

**Comment by toddself** [comment]
:laughing: 

Ah @yoshuawuyts you are my hero this morning!

Thanks again!

**Comment by toddself** [comment]
But after looking at the code I'm confused as to why this works?

It looks like including the base project actually calls custom with `process.env`, where as calling custom directly with no args short-circuits into `process.env`.

Any idea on why this actually works?

**Comment by yoshuawuyts** [comment]
I believe the files are used as follows:
- `./custom.js` is called for JS usage
- `./index.js` is called for `package.json` transforms (not completely sure about this though)
- `bin/envify` is called for CLI usage

Not entirely sure why this is how it is, pretty sure we could do a better job (':

**Comment by damncabbage** [comment]
For someone who stumbled across this ticket with the same confusing problem:

From the example:
```
browserify('entrypoint.js').transform(require('envify')()).bundle()
```

Should actually be:
```
browserify('entrypoint.js').transform(require('envify')).bundle()
         // No () here; it's already ready for use ---^
```

(The default version of `envify` is already "applied". I think this was a *little* unclear from the docs; the notation in the "Module Usage" headings was unfamiliar to me.)

**Comment by zekedroid** [comment]
@damncabbage: saved me after hours of debugging. This should go into the README.md.

**Comment by george-norris-salesforce** [comment]
Running into same problem. If can't use `()` how to pass in arguments?
```
b.transform(envify({
  NODE_ENV: 'development'
}))
```
