### ISSUE TITLE
(Bug or not?) Should it replace variables in expressions that are not comparisons?

### ISSUE THREAD

**Issue by alexeyraspopov** [hughsk/envify#34]
After using Envify as a Browserify's transform I still can see something like `var env = process.env.NODE_ENV || 'development';` in my code. Is it correct behavior or am I doing something wrong?

**Comment by zertosh** [comment]
sounds like you're doing something wrong - that should be transformed. do you something i can test/look at?

**Comment by alexeyraspopov** [comment]
@zertosh there is small gist that can be used for reproducing https://gist.github.com/alexeyraspopov/36efb2931bd1bb969510

**Comment by zertosh** [comment]
Ah, because envify isn't being run as a global transform. The way you're using it, it's only applied to your files, not your node_modules. Try `browserify index.js -t babelify -g envify`.

**Comment by alexeyraspopov** [comment]
Cool, it works! Thank you!
