### ISSUE TITLE
Is there a way to specify a custom object?

### ISSUE THREAD

**Issue by mbrevda** [hughsk/envify#36]
Let's say I'd rather not pollute my `process.env`. Is there a way to specify my own, custom, object to be operated on?

**Comment by yoshuawuyts** [comment]
Yup, from the docs:
```js
b.transform(envify({
  NODE_ENV: 'development'
}))
b.bundle().pipe(output)
```

**Comment by mbrevda** [comment]
I'm not sure I was clear. Instead of searching for `process.env.myVar`, I'd like to search for `foo.myVar`.

**Comment by yoshuawuyts** [comment]
Oh no can't do, that is not what this package is for. You're welcome to write your own transform. Cheers!

**Comment by mbrevda** [comment]
Thanks
