### ISSUE TITLE
Set environment variables from the file

### ISSUE THREAD

**Issue by vdemedes** [hughsk/envify#37]
Would be lovely, if envify supported setting env variables from the file (e.g. `.env`):

```
$ envify -f .env
```

.env:

```
VAR1=abc
VAR2=cba
```

Real use case: storing API keys for some services (e.g. MapBox) in `.env` file and wanting to replace `process.env.API_KEY` in code with those values.

**Comment by vdemedes** [comment]
Happy to submit a PR, if you also want this feature.

**Comment by yoshuawuyts** [comment]
I'm generally hesitant to endorse adding features to this package, but I feel this might be a useful addition to the cli. I'd be happy to review a PR on this.

**Comment by vdemedes** [comment]
It wouldn't be very useful if this feature remained only in CLI and not in the `lib/custom.js`, as (I assume) most people use envify as a browserify transformer (`browserify -t envify`).

**Comment by yoshuawuyts** [comment]
Oh yeah, that's what I meant. Just don't think reading files should be part of the js api, as that would mangle concerns.

**Comment by hughsk** [comment]
This functionality would be better implemented in a separate package, envify already has too many features as-is. See also: [envlocalify](https://www.npmjs.com/package/envlocalify).

**Comment by vdemedes** [comment]
No worries ;)

@hughsk Thanks for envlocalify reference.
