### ISSUE TITLE
process.env.npm_package_version not replaced

### ISSUE THREAD

**Issue by karelbilek** [hughsk/envify#49]
This is something between a question and an issue, since I am not sure how it should work.

I have in the code 

`var version = process.env.npm_package_version`

and I would expect envify to replace this with the npm package version. But it doesn't.

**Comment by tomachinz** [comment]
i also have this issue.

**Comment by yoshuawuyts** [comment]
@tomachinz make sure you're running this from within `npm scripts`. `$npm_package_version` is injected by npm, not by Node.
