### ISSUE TITLE
/custom not working

### ISSUE THREAD

**Issue by electerious** [hughsk/envify#55]
I've trouble getting the `envify/custom` version working. The following code bundles without errors, but still contains `process.env.NODE_ENV`. Nothing has been replaced:

```js
const envify = require('envify/custom')

/* browserify() */.transform(envify({

	NODE_ENV: 'production'

}))/* .bundle() */
```

The normal module however works fine.

```js
const envify = require('envify')

process.env.NODE_ENV = 'production'

/* browserify() */.transform(envify)/* .bundle() */
```

Is there a difference between setting `process.env.NODE_ENV = 'production'` and passing `NODE_ENV: 'production'` to the custom module?

---

Node v6.7.0
envify v4.0.0

All tests are passing on my setup.

**Comment by electerious** [comment]
I did something wrong. I don't know what, but it works now.

**Comment by electerious** [comment]
It's because this is missing in the documentation. It would have saved me some hours: https://github.com/hughsk/envify/pull/44

**Comment by Kryten0807** [comment]
Just to make it perfectly clear what the issue is:

    bundle.transform(envify({ NODE_ENV: 'production' }));

will "envify" your code but will **not** touch any packages imported from `node_modules`.

    bundle.transform(envify({ NODE_ENV: 'production' }), { global: true });

will "envify" both your code and packages from `node_modules`.

Thanks to @electerious for finding this and @MohsenEkhtiari for submitting a patch.
